# The fixture named here is intentionally absent. It must be generated by a dedicated ticket and
# identify the defs, pawns, terrain, and expected thoughts it installs before this feature runs.
@wip
Feature: RimScent Extended extension points and native scan additions

  Background:
    Given the fixture "rimscent-engine-regressions" is loaded
    And RimScent Extended scanner observations are reset

  Scenario: a pawn scent respects its configured stat threshold
    Given the fixture has a pawn scent source below its stat threshold
    When RimScent Extended runs one scent scan for the fixture observer
    Then RimScent Extended observes no pawn scent thought
    When the fixture raises the source above its stat threshold
    And RimScent Extended runs one scent scan for the fixture observer
    Then RimScent Extended observes the configured pawn scent thought

  Scenario: a scent hediff is refreshed while exposure continues
    Given the fixture has a scent source with a disappearing hediff extension
    When RimScent Extended runs repeated scans while the fixture observer remains exposed
    Then RimScent Extended observes one configured hediff with its disappearance timer refreshed
    When the fixture observer leaves exposure
    Then RimScent Extended observes the hediff expire without a stale scanner error

  Scenario: terrain scent counts tiles and honours its temperature gate
    Given the fixture surrounds the observer with configured scent terrain
    When RimScent Extended runs one scent scan at the terrain's allowed temperature
    Then RimScent Extended observes the configured terrain thought at the expected tile count
    When the fixture changes temperature below the terrain gate
    And RimScent Extended runs one scent scan
    Then RimScent Extended observes no gated terrain thought

  Scenario: corpses and spoiled food use their rot-stage thoughts
    Given the fixture places fresh, rotting, and dessicated corpses near separate observers
    And the fixture places spoiled food near a fourth observer
    When RimScent Extended runs one scent scan for each observer
    Then RimScent Extended observes the matching corpse thought for each rot stage
    And RimScent Extended observes the configured spoiled-food thought
